// lista de fronteiras
export const fronteiras = {
  
      "Africa do Sul": ["Madagascar", "Sudao", "Congo"],
      Alemanha: ["Inglaterra", "Polonia", "Espanha"],
      Argentina: ["Brasil", "Bolivia", "Chile"],
      Brasil: ["Argentina", "Bolivia", "Colombia", "Chile", "Nigeria"],
      Bolivia: ["Chile", "Brasil", "Argentina"],
      Canada: ["Estados Unidos", "Groelandia","Russia Oriental"],
      Chile: ["Colombia", "Brasil", "Bolivia", "Argentina"],
      China: ["Russia Oriental", "India", "Japao","Mongolia","Viatna"],
      Colombia: ["Mexico", "Brasil", "Chile"],
      Congo: ["Nigeria", "Africa do Sul", "Sudao"],
      Egito: ["Sudao", "Nigeria", "Marrocos", "Polonia", "Oriente Medio", "Espanha"],
      Espanha: ["Alemanha","Inglaterra", "Polonia", "Marrocos", "Egito"],
      "Estados Unidos": ["Canada", "Mexico"],
      Groelandia: ["Islandia", "Canada","Groenlandia"],
      India: ["China", "Oriente Médio", "Russia Oriental", "Viatna"],
      Irlanda: ["Inglaterra"],
      Islandia: ["Suecia", "Inglaterra"],
      Inglaterra: ["Islandia", "Espanha", "Alemanha", "Irlanda", "Polonia"],
      Japao: ["China", "Russia Oriental"],
      Madagascar: ["Africa do Sul"],
      Marrocos: ["Egito", "Nigeria", "Espanha"],
      Mexico: ["Colombia", "Estados Unidos"],
      Nigeria: ["Sudao", "Congo", "Marrocos", "Egito", "Brasil"],
      "Nova Zelandia": ["Australia", "Viatna"],
      Polonia: ["Alemanha", "Egito", "Espanha", "Russia Ocidental","Oriente Médio"],
      "Russia Ocidental": ["Suecia", "Polonia", "Oriente Médio", "Russia Oriental"],
      "Russia Oriental": ["Mongolia","Canada","China", "Russia Ocidental", "India", "Japao", "Oriente Médio"],
      Suecia: ["Islandia", "Russia Ocidental"],
      "Oriente Médio": ["Egito", "India", "Polonia", "Russia Ocidental", "Russia Oriental"],
      Sudao: ["Congo", "Africa do Sul", "Nigeria", "Egito"],
      Viatna: ["India", "China", "Nova Zelandia"],

    };