// lista de fronteiras
export const fronteiras = {
  
      "Africa do Sul": ["Madagascar", "Sudao", "Congo"],
      Alemanha: ["Inglaterra", "Polonia", "Espanha"],
      Argentina: ["Brasil", "Bolivia", "Chile"],
      Australia: ["Indonesia", "Ilhas Salomao", "Singapura"],
      Bolivia: ["Chile", "Brasil", "Argentina"],
      Brasil: ["Argentina", "Bolivia", "Colombia", "Chile", "Nigeria"],
      Canada: ["Estados Unidos", "Groelandia","Russia Oriental"],
      Chile: ["Colombia", "Brasil", "Bolivia", "Argentina"],
      China: ["Russia Oriental", "India", "Japao","Mongolia","Vietna"],
      Colombia: ["Mexico", "Brasil", "Chile"],
      Congo: ["Nigeria", "Africa do Sul", "Sudao"],
      Egito: ["Sudao", "Nigeria", "Marrocos", "Polonia", "Oriente Medio", "Espanha"],
      Espanha: ["Alemanha","Inglaterra", "Polonia", "Marrocos", "Egito"],
      "Estados Unidos": ["Canada", "Mexico"],
      Groelandia: ["Islandia", "Canada"],
      "Ilhas Salomao": ["Australia", "Papua Nova-Guine"],
      India: ["China", "Oriente Médio", "Russia Oriental", "Vietna", "Malasia"],
      Indonesia: ["Australia", "Papua Nova-Guine"],
      Inglaterra: ["Islandia", "Espanha", "Alemanha", "Irlanda", "Polonia"],
      Irlanda: ["Inglaterra"],
      Islandia: ["Suecia", "Inglaterra", "Groelandia"],
      Japao: ["China", "Russia Oriental"],
      Madagascar: ["Africa do Sul"],
      Malasia: ["Singapura", "India"],
      Marrocos: ["Egito", "Nigeria", "Espanha"],
      Mexico: ["Colombia", "Estados Unidos"],
      Mongolia: ["Russia Oriental", "China"],
      Nigeria: ["Sudao", "Congo", "Marrocos", "Egito", "Brasil"],
      "Nova Zelandia": ["Australia", "Vietna"],
      "Oriente Médio": ["Egito", "India", "Polonia", "Russia Ocidental", "Russia Oriental"],
      "Papua Nova-Guine": ["Ilhas Salomao", "Indonesia"],
      Polonia: ["Alemanha", "Egito", "Espanha", "Russia Ocidental","Oriente Médio"],
      "Russia Ocidental": ["Suecia", "Polonia", "Oriente Médio", "Russia Oriental"],
      "Russia Oriental": ["Mongolia","Canada","China", "Russia Ocidental", "India", "Japao", "Oriente Médio"],
      Singapura: ["Malasia", "Australia"],
      Sudao: ["Congo", "Africa do Sul", "Nigeria", "Egito"],
      Suecia: ["Islandia", "Russia Ocidental"],
      Vietna: ["India", "China", "Nova Zelandia", "Indonesia"],

    };